---
author: "Sihle"
title: "Assignments"
output: github_document
---
#Assignment 2

```{r quick_loo, echo=TRUE}
data("anscombe")
dim(anscombe)
names(anscombe)
head(anscombe)
tail(anscombe)
summary(anscombe)

```

#Assignment 3


```{r xy_plot, echo=FALSE, fig.height=8, fig.width=8, fig.align='center', fig.ext='svg', fig.path='./figures/'}

data("anscombe")
plot(anscombe$x1, anscombe$y1, xlab = 'x1', ylab = 'y1', pch = 22, col = 'green')
abline(lm(y1~x1, data=anscombe), lwd=2, col = 'grey')


```

#Assignment 4
##Chunk 1

```{r  data_import, echo=TRUE}

analgesicdf <- read.csv('analgesic.csv')
analgesicdf

```

##Chunk 2
```{r data_summary, echo=TRUE}
analgesicdf
dim(analgesicdf)
names(analgesicdf)
head(analgesicdf)
tail(analgesicdf)
summary(analgesicdf)

```

##Chunk 3
```{r data_tidy, echo=TRUE}
library(dplyr)
library(tidyr)

df1<-gather(analgesicdf, key = One, value = Two, Measurement_1, Measurement_2, Measurement_3)
df2<-group_by(df1, ID, Group)
df3<-summarise(df2, mean(Two))

```

